In [3]:
import numpy as np
import math
from hrr import hrr
from scipy.spatial.transform import Rotation as rotate

In [4]:
def cosine_similarity(vec_a, vec_b):
    return np.dot(vec_a, vec_b) / np.linalg.norm(vec_a) * np.linalg.norm(vec_b)

In [7]:
n = 16  # number of neurons

In [8]:
preferred_directions = np.linspace(0, 2 * np.pi, n, endpoint=False)  # create direction angles (in radians)
print("Radians: " + str(preferred_directions))
print("Degrees: " + str(np.degrees(preferred_directions)))


Radians: [0.         0.39269908 0.78539816 1.17809725 1.57079633 1.96349541
 2.35619449 2.74889357 3.14159265 3.53429174 3.92699082 4.3196899
 4.71238898 5.10508806 5.49778714 5.89048623]
Degrees: [  0.   22.5  45.   67.5  90.  112.5 135.  157.5 180.  202.5 225.  247.5
 270.  292.5 315.  337.5]


In [49]:
direction_vectors = np.array([
    [np.sin(theta), np.cos(theta), 0]  # z-component is zero, for now
    for theta in preferred_directions
])
print(direction_vectors)

[[ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 7.07106781e-01  7.07106781e-01  0.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00]
 [ 7.07106781e-01 -7.07106781e-01  0.00000000e+00]
 [ 1.22464680e-16 -1.00000000e+00  0.00000000e+00]
 [-7.07106781e-01 -7.07106781e-01  0.00000000e+00]
 [-1.00000000e+00 -1.83697020e-16  0.00000000e+00]
 [-7.07106781e-01  7.07106781e-01  0.00000000e+00]]


In [55]:
'''
how much do neurons fire for a direction? 
- 1 for same
- 0 for complete opposite
- how do we do in between? --> gaussian or von Mises function

important to note that in npv paper the population vectors started with small magitude and increased as the turn completed (increase looks like y = logx graph)
'''

θ_target = np.radians(90)
target_vector = np.array([np.sin(θ_target), np.cos(θ_target), 0])
θ_current = np.radians(0)
current_vector = np.array([np.sin(θ_current), np.cos(θ_current), 0])

print(target_vector, current_vector)
print(cosine_similarity(current_vector, target_vector))

step_size = 5
rotation_axis = np.array([0, 0, 1])     # z-axis for now
direction = -1                          # -1 = left, 1 = right
r = rotate.from_rotvec([0, 0, np.radians(direction * step_size)]) # quaternion representing 5 deg rotation around z-axis

### LOOP #### 

while cosine_similarity(current_vector, target_vector) < 0.95:     # checking cosine similarity
    print(cosine_similarity(current_vector, target_vector))

    # re-adjust axis of rotation

    # calculate population vector
    firing_rates = [0.5 * (math.cos(θ_current - θ_i) + 1) for θ_i in preferred_directions]  # use gaussian or von Mises function rather than cos() for more biologically accurate firing rates
    print(firing_rates)
    population_vector = sum(firing_rates[i] * direction_vectors[i] for i in range(n))
    print(population_vector)

    # update current vector
    current_vector = r.apply(current_vector)
    print(current_vector)

    θ_current = θ_current + np.radians(step_size)

# '''
# perform rotation using rotation matrix or quaternions?
# - chatgpt suggested quaternions (better for multiple small rotations)
# - import from scipy
# '''
print("hello")

[1.000000e+00 6.123234e-17 0.000000e+00] [0. 1. 0.]
6.123233995736766e-17
6.123233995736766e-17
[1.0, 0.8535533905932737, 0.5, 0.14644660940672627, 0.0, 0.14644660940672616, 0.4999999999999999, 0.8535533905932737]
[0. 2. 0.]
[0.08715574 0.9961947  0.        ]
0.08715574274765824
[0.9980973490458728, 0.883022221559489, 0.5435778713738291, 0.17860619515673032, 0.0019026509541272274, 0.116977778440511, 0.4564221286261709, 0.8213938048432696]
[0.17431149 1.9923894  0.        ]
[0.17364818 0.98480775 0.        ]
0.17364817766693041
[0.9924038765061041, 0.909576022144496, 0.5868240888334653, 0.21321178182447692, 0.00759612349389599, 0.0904239778555041, 0.41317591116653485, 0.786788218175523]
[0.34729636 1.96961551 0.        ]
[0.25881905 0.96592583 0.        ]
0.25881904510252085
[0.9829629131445341, 0.9330127018922193, 0.6294095225512604, 0.2500000000000001, 0.0170370868554659, 0.06698729810778059, 0.3705904774487397, 0.75]
[0.51763809 1.93185165 0.        ]
[0.34202014 0.93969262 0.       